spring:
  application:
    name: retoaws-person-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": false

server:
  port: ${SERVER_PORT:8092}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    "[com.talentpool.retoaws]": INFO
    "[org.springframework.web]": INFO