spring:
  config:
    activate:
      on-profile: prod
    import:
      - "aws-secretsmanager:retoaws/prod/database/credentials"
      - "aws-parameterstore:"
      
  cloud:
    aws:
      credentials:
        instance-profile: true
      region:
        static: us-east-1
      
  datasource:
    url: jdbc:mysql://${/retoaws/prod/database/host}:${/retoaws/prod/database/port}/${/retoaws/prod/database/name}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
      
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-prod.sql

server:
  port: ${/retoaws/prod/server/port}

logging:
  level:
    "[com.talentpool.retoaws]": DEBUG
    "[org.hibernate.SQL]": WARN
    "[org.springframework.web]": DEBUG
    "[org.apache.catalina]": DEBUG