spring:
  application:
    name: retoaws-person-api
  profiles:
    active: ${/retoaws/prod/spring/profiles/active:dev}
  
  jpa:
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": false

server:
  port: ${/retoaws/prod/server/port:8191}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
logging:
  level:
    "[com.talentpool.retoaws]": INFO
    "[org.springframework.web]": INFO