spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-prod.sql

server:
  port: ${SERVER_PORT}

logging:
  level:
    "[com.talentpool.retoaws]": DEBUG
    "[org.hibernate.SQL]": WARN
    "[org.springframework.web]": DEBUG
    "[org.apache.catalina]": DEBUG